# This is a rough example of using Okta as the authorization server as part of a SMART/FHIR deployment.
# It includes the following features:
# - standalone launch with launch parameters
# - a patient picker screen and OAuth2 scope selection and consent.
# - applicable proxies for properly handling public client authentication as well as returning launch parameters in a flexible way.
# - passthrough API endpoints for demo data, hosted by HAPI.org.

service: auth0-ref-smart-service

package:
  exclude:
    - deploy/**
    - serverless*.yml

plugins:
  - serverless-certificate-creator
  - serverless-domain-manager

params:
  default:
    AWS_REGION: us-east-1

    #The domain name you want publicly as the base domain name.
    BASE_DOMAIN: authz.your.tld
    #Route53 hosted domain (include the period at the end)
    BASE_URL_TLD: your.tld.
    #The auth0 custom backend domain name for auth0 custom domain names.
    AUTH0_CUSTOM_DOMAIN_NAME_BACKEND: get-value-from-custom-domain-setup.edge.tenants.us.auth0.com
    #The auth0 custom domain name api key.
    AUTH0_CUSTOM_DOMAIN_NAME_APIKEY: get this value from a0 custom domain setup
    #The backend domain name for the api gateway deployment.
    API_GATEWAY_DOMAIN_NAME_BACKEND: get this value from serverless create_domain output

    #A hash secret used to hash refresh token contents stored in auth0
    #Make sure this matches the REFRESH_TOKEN_HASH_SECRET in config.json!
    REFRESH_TOKEN_SIGNING_KEY: YouShouldUseAReallyLongValueHereThisisUsedtoHashRefreshTokens

provider:
  name: aws
  runtime: nodejs18.x
  stage: demo
  region: ${param:AWS_REGION}

  logs:
    restApi: true


  environment:
    REFRESH_TOKEN_SIGNING_KEY: ${param:REFRESH_TOKEN_SIGNING_KEY}
    AUTH0_CUSTOM_DOMAIN_NAME_BACKEND: ${param:AUTH0_CUSTOM_DOMAIN_NAME_BACKEND}
    AUTH0_CUSTOM_DOMAIN_NAME_APIKEY: ${param:AUTH0_CUSTOM_DOMAIN_NAME_APIKEY}

#Lambda functions
functions:

##TOKEN ENDPOINT
  smart-token-proxy:
    handler: ${self:provider.name}/token.tokenHandler
    events:
      - http:
          path: /oauth/token
          method: POST
          cors: true

custom:
  customCertificate:
    certificateName: ${param:BASE_DOMAIN}
    hostedZoneNames: ${param:BASE_URL_TLD}
    subjectAlternativeNames:
      - ${param:BASE_DOMAIN}

  customDomain:
    domainName: ${param:BASE_DOMAIN}
    certificateName: ${param:BASE_DOMAIN}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: regional

resources:
  Resources:
    authzServiceCFDistribution:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          Aliases:
          - ${param:BASE_DOMAIN}
          Origins:
          - #THIS ONE IS THE API GATEWAY
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: "https-only"
              OriginReadTimeout: 30
              OriginSSLProtocols:
              - "TLSv1.2"
            DomainName: ${param:API_GATEWAY_DOMAIN_NAME_BACKEND}
            Id: ${param:API_GATEWAY_DOMAIN_NAME_BACKEND}
            OriginPath: ""
          - #THIS ONE IS AUTH0
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: "https-only"
              OriginReadTimeout: 30
              OriginSSLProtocols:
              - "TLSv1.2"
            DomainName: ${param:AUTH0_CUSTOM_DOMAIN_NAME_BACKEND}
            Id: ${param:AUTH0_CUSTOM_DOMAIN_NAME_BACKEND}
            OriginCustomHeaders:
            -
              HeaderName: "cname-api-key"
              HeaderValue: ${param:AUTH0_CUSTOM_DOMAIN_NAME_APIKEY}
            OriginPath: ""
          DefaultCacheBehavior:
            AllowedMethods:
            - "HEAD"
            - "DELETE"
            - "POST"
            - "GET"
            - "OPTIONS"
            - "PUT"
            - "PATCH"
            CachedMethods:
            - "HEAD"
            - "GET"
            Compress: false
            DefaultTTL: 86400
            ForwardedValues:
              Cookies:
                Forward: "all"
              Headers:
              - "Authorization"
              - "Origin"
              - "Accept"
              - "User-Agent"
              - "Referer"
              - "Accept-Language"
              QueryString: true
            MaxTTL: 31536000
            MinTTL: 0
            SmoothStreaming: false
            TargetOriginId: ${param:AUTH0_CUSTOM_DOMAIN_NAME_BACKEND}
            ViewerProtocolPolicy: "redirect-to-https"
            FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: 
                Fn::GetAtt: audienceRewriteFunction.FunctionMetadata.FunctionARN
          CacheBehaviors:
          -
            AllowedMethods:
            - "HEAD"
            - "DELETE"
            - "POST"
            - "GET"
            - "OPTIONS"
            - "PUT"
            - "PATCH"
            Compress: false
            CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
            OriginRequestPolicyId: "216adef6-5c7f-47e4-b989-5492eafa07d3"
            PathPattern: "/oauth/token"
            SmoothStreaming: false
            TargetOriginId: ${param:API_GATEWAY_DOMAIN_NAME_BACKEND}
            ViewerProtocolPolicy: "https-only"
          Comment: ""
          PriceClass: "PriceClass_All"
          Enabled: true
          ViewerCertificate:
            AcmCertificateArn: ${certificate(${self:custom.customCertificate.certificateName}):CertificateArn}
            MinimumProtocolVersion: "TLSv1.2_2021"
            SslSupportMethod: "sni-only"
          Restrictions:
            GeoRestriction:
              RestrictionType: "none"
          HttpVersion: "http2"
          DefaultRootObject: ""
          IPV6Enabled: false

    audienceRewriteFunction:
      Type: AWS::CloudFront::Function
      Properties:
        AutoPublish: true
        FunctionCode: |
          function handler(event) {
            var request = event.request;
            var qs = request.querystring;

            if (qs.aud && qs.aud.value) {
                request.querystring["audience"] = {"value": qs.aud.value};
            }
    
            return request;
          }
        FunctionConfig:
          Runtime: cloudfront-js-1.0
          Comment: "Rewrite aud (SMART) to audience (Auth0)"
        Name: 
          Fn::Sub: "${AWS::StackName}-audienceRewriteFunction"